# Generated by Django 3.1.3 on 2021-05-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favamealapi', '0003_restaurant_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='favorites',
        ),
    ]
