# Generated by Django 3.1.3 on 2021-05-12 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0004_remove_restaurant_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorites',
            field=models.ManyToManyField(through='favamealapi.FavoriteRestaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
