# Generated by Django 3.1.3 on 2021-05-12 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0005_restaurant_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favorites',
            field=models.ManyToManyField(through='favamealapi.FavoriteMeal', to=settings.AUTH_USER_MODEL),
        ),
    ]
